server {
    listen 80;
    listen 443;
    server_name example.com;
	server_name www.example.com;

    #root /var/www/example; # no support for root in server block yet, should be overridden by location root if both exist
    #index index.html index.htm; # no support for index in server block yet, should be overridden by location index if both exist

    error_page 404 /404.html;
    #error_page 500 502 503 504 /50x.html; # no support for multiple error codes for the same page yet

    #access_log /var/log/server/access.log; #
    #error_log /var/log/server/error.log;

    client_max_body_size 10M;

    location / {
        #try_files $uri $uri/ =404;
    }

    location /images/ {
        root /var/www/images;
        autoindex on; # Enabling or disabling directory listing.
    }

    location /upload/ {
        methods POST;
        upload_store /var/www/uploads;
    }

    location /cgi-bin/ {
        cgi .py /usr/bin/python3;
        cgi .php /usr/bin/php-cgi;
    }

    location /old-page {
        return 301 /new-page;
    }
}
