server {
	# Define all the interface:port pairs on which your server will listen to (defining multiple websites served by your program).
    listen 127.0.0.1:8080;
	listen 127.0.0.1:8081;
	listen 127.1.2.3:8082;
	listen 8083; # if we specify a port without an ip address, it defaults to 0.0.0.0 to mimic nginx behavior
	# TODO:
	#listen [::]:8080; # support for IPv6 addresses
	#listen 127.4.5.6; # if we specify an ip address without a port, it should default to 80 to mimic nginx behavior

	# Set up default error pages
    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

	# Set the maximum allowed size for client request bodies.
    client_max_body_size 10M;

	# Server name (not mandatory, but useful for virtual hosting).
	server_name example.com;

	# Specify rules or configurations on a URL/route (no regex required here), for a website, among the following:
    location / {
		# List of accepted HTTP methods for the route.
        methods GET POST;
		# Directory where the requested file should be located (e.g., if URL /kapouet is rooted to /tmp/www, URL /kapouet/pouic/toto/pouet will search for /tmp/www/pouic/toto/pouet).
        root /var/www/html;
		# Default file to serve when the requested resource is a directory.
        index index.html;
		# Enabling or disabling directory listing.
        autoindex off;
    }

	# Uploading files from the clients to the server is authorized, and storage location is provided.
    location /upload {
        methods POST DELETE;
        root /var/www/uploads;
        upload_store /var/www/uploads;
    }

    location /old-page {
		# HTTP redirection
        return 301 /new-page;
    }

	# Execution of CGI, based on file extension (for example .php).
    location /cgi-bin {
        methods GET POST;
        root /var/www/cgi-bin;
        cgi .php /usr/bin/php-cgi;
        cgi .py /usr/bin/python3;
    }
}


server {
    listen 8081;
    error_page 404 /errors/404.html;
    client_max_body_size 1M;

    location / {
        methods GET;
        root /var/www/site2;
        index index.html;
        autoindex on;
    }
}
